# Generated by Django 3.2.6 on 2021-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Product name')),
                ('image', models.CharField(max_length=250, verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product price')),
                ('sold_out', models.BooleanField(default=False, verbose_name='Product is sold out')),
            ],
        ),
    ]
